# Generated by Django 5.1.6 on 2025-02-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='num_tickets',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
